version: "2"
  
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  ssl:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"

  jira:
    image: atlassian/jira-software:8.20
    container_name: jira
    restart: always
    environment:
      - VIRTUAL_HOST=${domain}
      - VIRTUAL_PORT=8080
      - ATL_PROXY_NAME=${domain}
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - LETSENCRYPT_HOST=${domain}
      - LETSENCRYPT_EMAIL=${email}
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira

volumes:
  jiraVolume:
    external: false